# Generated by Django 3.2.12 on 2022-04-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseStudy',
        ),
    ]
