# Generated by Django 3.2.12 on 2022-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
