# Generated by Django 3.2.12 on 2022-04-25 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('shared_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.CharField(default='0', max_length=200, null=True)),
                ('case', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
