# Generated by Django 4.0.4 on 2022-12-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_comment_alter_case_options_case_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
