# Generated by Django 4.0.4 on 2022-11-29 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0006_alter_case_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='case',
            field=models.ForeignKey(default=0.0013038395827713334, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quiz.case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='comment_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
