# Generated by Django 4.0.4 on 2022-12-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_comment_dislikes_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseresult',
            name='scored',
            field=models.BooleanField(default=False),
        ),
    ]
