# Generated by Django 3.2.12 on 2022-04-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
