# Generated by Django 3.2.12 on 2022-04-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
