# Generated by Django 3.2.12 on 2022-04-08 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='collaborative_members',
            field=models.ManyToManyField(related_name='collaborative_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
