# Generated by Django 3.2.12 on 2022-04-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_course_collaborative_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
