# Generated by Django 3.2.12 on 2022-04-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
