# Generated by Django 3.2.12 on 2022-04-09 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0009_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='collaborative_members',
            field=models.ManyToManyField(blank=True, related_name='collaborative_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
