# Generated by Django 3.2.12 on 2022-04-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_course_collaborative_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='This is my bio!'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='../templates/userprofile/icons/1200px-Circle-icons-profile.svg.png', upload_to='images'),
        ),
    ]
