# Generated by Django 3.2.12 on 2022-04-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
