# Generated by Django 3.2.12 on 2022-04-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_lecture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='userprofile.course'),
        ),
    ]
