# Generated by Django 4.0.4 on 2022-10-23 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Outside', 'Outside'), ('Workshop', 'Workshop'), ('Social', 'Social'), ('Presentation', 'Presentation'), ('Introductory', 'Introductory'), ('Training', 'Training')], default='Workshop', max_length=12),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(default='http://www.helloworld.com'),
        ),
    ]
