# Generated by Django 4.0.4 on 2022-11-05 18:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
