# Generated by Django 4.0.4 on 2022-10-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0027_remove_event_start_time_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(help_text='event_image', null=True, upload_to='images'),
        ),
    ]
