# Generated by Django 4.0.4 on 2022-11-06 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0029_event_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Outside', 'Outside'), ('Workshop', 'Workshop'), ('Social', 'Social'), ('Presentation', 'Presentation'), ('Introductory', 'Introductory'), ('Training', 'Training')], default='Workshop', max_length=12),
        ),
    ]
