# Generated by Django 4.0.4 on 2022-11-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0030_event_published_date_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
