# Generated by Django 4.0.4 on 2022-11-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0034_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
