# Generated by Django 4.0.4 on 2022-11-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0035_alter_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Outside', 'Outside'), ('Workshop', 'Workshop'), ('Social', 'Social'), ('Presentation', 'Presentation'), ('Introductory', 'Introductory'), ('Training', 'Training'), ('Others', 'Others')], default='Workshop', max_length=12),
        ),
    ]
